// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe7tbhGlGNM9x4SrV0OnXdg1NlQQYCwcE',
    appId: '1:20781046770:web:aae8be92b9fcebdc4da96b',
    messagingSenderId: '20781046770',
    projectId: 'sustainable-living-guide-28d49',
    authDomain: 'sustainable-living-guide-28d49.firebaseapp.com',
    storageBucket: 'sustainable-living-guide-28d49.firebasestorage.app',
    measurementId: 'G-8BF1YK5VPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVRpr09BzbF-cXtUn-J6QQqv7xeAmvklY',
    appId: '1:20781046770:android:1da40d29d35f51c44da96b',
    messagingSenderId: '20781046770',
    projectId: 'sustainable-living-guide-28d49',
    storageBucket: 'sustainable-living-guide-28d49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkej_-oKBzl1B5W-lUn6qCPFBNvpAHik',
    appId: '1:20781046770:ios:2283622c6c494a9b4da96b',
    messagingSenderId: '20781046770',
    projectId: 'sustainable-living-guide-28d49',
    storageBucket: 'sustainable-living-guide-28d49.firebasestorage.app',
    iosBundleId: 'com.example.sustainable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkej_-oKBzl1B5W-lUn6qCPFBNvpAHik',
    appId: '1:20781046770:ios:2283622c6c494a9b4da96b',
    messagingSenderId: '20781046770',
    projectId: 'sustainable-living-guide-28d49',
    storageBucket: 'sustainable-living-guide-28d49.firebasestorage.app',
    iosBundleId: 'com.example.sustainable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe7tbhGlGNM9x4SrV0OnXdg1NlQQYCwcE',
    appId: '1:20781046770:web:ef4057353a98e2a44da96b',
    messagingSenderId: '20781046770',
    projectId: 'sustainable-living-guide-28d49',
    authDomain: 'sustainable-living-guide-28d49.firebaseapp.com',
    storageBucket: 'sustainable-living-guide-28d49.firebasestorage.app',
    measurementId: 'G-2P0S7WYXQ9',
  );
}
